### ISSUE TITLE
[DI1]

### ISSUE THREAD

**Issue by adrianmg89** [kakawe/kakawe#3]
Análisis y especificaciones del diseño atendiendo a criterios de usabilidad y buscando una experiencia de usuario óptima.

**Comment by McCrash** [comment]
diseño persona caso de uso
![1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ac568d2b07ea1a0077d08a/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1281373772b01f22876d2b478ef122b500d5e1ca4125b5756e0ebcb7af8e2632dd3165eafc3674d75c13710a9b98717bc09be218b4a84bfaec7.PNG)

Caracteristicas
![2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ac568d2b07ea1a0077d08a/125516c66e82c728ace21e0d46bad6d6619291a685ecbc57e607b2c1281373772b01f22876d2b478ef122b500d5e1ca4125b5756e0ebcb7af8e2632dd3165eafc3674d75c13710a9b98717bc09bd23884783b5aec7.PNG)

**Comment by McCrash** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DI1]](https://trello.com/c/zJ1Wivfd/2-di1)
